### ISSUE TITLE
End of game resolved before some extra actions

### ISSUE THREAD

**Issue by stevasale** [joffrey-bion/seven-wonders#122] opened 2021-02-12 13:09 UTC
At the end of the game, the points for war are counted before all (extra) player actions are resolved, potentially leading to wrong war results.
For example, having the ability to pick up a card from the discard pile is performed after the war points are counted. If a red card is picked in this example, it is de-facto ignored at the end of the game

**Comment by joffrey-bion** [comment] 2021-02-12 18:15
Thanks a lot for this report. There were already some glitches like this in the past, but I thought I had fixed the issue.

The case of the discarded cards is actually specifically handled before end of game events, which is why I'm surprised to see you have this bug. I will look again.
This area (about the game state / extra actions) needs to be reworked anyway, it was on my todo list :)

**Comment by joffrey-bion** [comment] 2021-02-13 15:25
@stevasale I can't reproduce your exact example. I'm playing Halikarnassus B, and using the last turn of the game to upgrade the wonder, and pick a war card from the discard pile to get my military up to win over my neighbours.
It did work, and the score reflects it.

Could you please elaborate on how you saw this problem?

**Comment by stevasale** [comment] 2021-02-15 08:23
I am sorry if those cases which can influence the outcome of the war are already taken care of. I just saw that the war points were already calculated even though not all extra player actions were done and assumed from there, that potentially something could go wrong. 
The example given was just the most obvious case that came to mind.
However, if the extra actions of Babylon B or Olympia B are performed after the war points have been calculated, then still something could go wrong.
Come to think of it, i think I noticed this with Babylon B, where the seventh card I picked was a war card, and it was literally pointless. However, it's been quite some time ago, so I am not too sure any more.

**Comment by joffrey-bion** [comment] 2021-02-15 13:17
Thanks a lot for the precisions. I just tested and you are actually right regarding Babylon B and Olympia B.
For some reason their effect is not reflected in the score board (it's not just about war actually, copying guilds should give points).

There is actually an even worse issue with Babylon B:
https://github.com/joffrey-bion/seven-wonders/issues/125

**Comment by joffrey-bion** [comment] 2021-02-16 01:13
I'm closing this issue for the 2 more specific ones.

**Closed by joffrey-bion** 2021-02-16 01:13 UTC
Labels: bug, duplicate
